# Generated by Django 4.2.5 on 2023-09-17 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BoatRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bix_id', models.CharField(max_length=50)),
                ('license_number', models.CharField(max_length=50)),
                ('aadhar_number', models.CharField(max_length=12)),
                ('duration', models.CharField(max_length=50)),
                ('boat_type', models.CharField(max_length=50)),
                ('token', models.CharField(blank=True, max_length=22)),
            ],
        ),
    ]
